# Generated by Django 3.2.6 on 2021-08-16 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('plot', models.TextField()),
                ('year', models.PositiveBigIntegerField()),
                ('rating', models.IntegerField(choices=[(0, 'NR - Not Rated'), (1, 'G - General Audience'), (2, 'PR - Parental Guidance Suggested'), (3, 'R - Restricted')], default=0)),
                ('run_time', models.PositiveBigIntegerField()),
                ('website', models.URLField(blank=True)),
            ],
        ),
    ]
