# Generated by Django 3.2.6 on 2021-08-31 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_movieimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='value',
            field=models.SmallIntegerField(choices=[('UP', 'UP'), ('DOWN', 'DOWN')]),
        ),
    ]
