# Generated by Django 3.2.6 on 2021-08-31 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_vote_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='value',
            field=models.SmallIntegerField(choices=[(1, 'UP'), (-1, 'DOWN')]),
        ),
    ]
